name: news_hub
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  serious_python: ^0.8.4
  logger: ^2.5.0
  http: ^1.2.2
  sqflite: ^2.4.1
  flutter_downloader: ^1.11.8
  rxdart: ^0.28.0
  archive: ^3.6.1
  dio: ^5.7.0
  rx_shared_preferences: ^4.0.0
  dartx: ^1.2.0
  path_provider: ^2.1.5
  timeago: ^3.7.0
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  auto_route: ^9.3.0+1
  easy_stepper: ^0.8.5+1
  infinite_scroll_pagination: ^4.1.0
  grpc: ^4.0.1
  drift: ^2.25.0
  drift_flutter: ^0.2.4
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable: ^2.5.0
  url_launcher: ^6.3.1
  cached_query: ^2.2.1
  swipe_image_gallery: ^0.10.1
  youtube_player_flutter: ^9.1.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  protobuf: ^4.2.0
  fixnum: ^1.1.1
  uuid: ^4.5.2
  path: ^1.9.1
  permission_handler: ^12.0.1
  collection: ^1.19.1
  async: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  drift_dev: ^2.25.1
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - sidecar/dist/

analyzer:
  errors:
    invalid_annotation_target: ignore

flavorizr:
  flavors:
    sidecar:
      app:
        name: "News Hub Sidecar"
      android:
        flavorName: sidecar
        applicationId: "tw.kevinzhang.news_hub.sidecar"
      ios:
        bundleId: "tw.kevinzhang.news_hub.sidecar"
    remote:
      app:
        name: "News Hub Remote"
      android:
        flavorName: remote
        applicationId: "tw.kevinzhang.news_hub.remote"
      ios:
        bundleId: "tw.kevinzhang.news_hub.remote"
